<a href="https://colab.research.google.com/github/kumastry/maxrect/blob/main/maxrect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/kumastry/maxrect.git

Cloning into 'maxrect'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 23 (delta 6), reused 22 (delta 5), pack-reused 0
Unpacking objects: 100% (23/23), done.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
import os
print("カレントワーキングディレクトリは[" + os.getcwd() + "]です")
_colab_dir = "/content/drive/MyDrive/Colab Notebooks"
os.chdir(_colab_dir)
print("カレントワーキングディレクトリは[" + os.getcwd() + "]です")

カレントワーキングディレクトリは[/content/maxrect]です
カレントワーキングディレクトリは[/content/drive/MyDrive/Colab Notebooks]です


In [11]:
from myModule import maxrect
import networkx

m1 = maxrect.maxrect()
m1.ready()
m1.printResult()

1
[1 1 1 1 1]
[1]
[0 1 2 3 4]
-1
###
1
[1 1 1 0 0]
[1 0]
[0 1 2]
1
###
1
[0 0 1 1 1]
[1 0 2]
[2]
-1
###
2
[0 0 1 1 1]
[2]
[2 3 4]
-1
###
2
[1 1 1 1 1]
[2 1]
[2 3 4]
0
###
2
[1 1 1 0 0]
[2 1 0]
[2]
-3
###
3
[1 1 1 0 0]
[0]
[0 1 2]
-4
###
3
[1 1 1 1 1]
[0 1]
[0 1 2]
-5
###
3
[0 0 1 1 1]
[0 1 2]
[2]
-4
###
4
[1 1 1 1 1]
[1]
[0 1 2 3 4]
-6
###
4
[0 0 1 1 1]
[1 2]
[2 3 4]
-5
###
5
[0 0 1 1 1]
[2]
[2 3 4]
-4
###
[[array([1, 0]) array([0, 1, 2])]
 [array([2, 1]) array([2, 3, 4])]]


/content/drive/MyDrive/Colab Notebooks/myModule/maxrect.py:55: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.ec = np.append(self.ec, np.array([[S_max], [T_max]]))
